// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuk_4mOR8VDzFYKUj4hIiUGVoEpdoavM',
    appId: '1:75185627539:web:412ca3cab7f3e80f024866',
    messagingSenderId: '75185627539',
    projectId: 'miss-cady-7f1a1',
    authDomain: 'miss-cady-7f1a1.firebaseapp.com',
    storageBucket: 'miss-cady-7f1a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpSx1GIytN2ta7ho5yDlnydEO6QMOWj0',
    appId: '1:584741101684:android:ad307a68bd1af9d6357121',
    messagingSenderId: '584741101684',
    projectId: 'miss-cady-production',
    storageBucket: 'miss-cady-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChElLsZDGgPJNdY5rddFSvmclmykmTOoI',
    appId: '1:584741101684:ios:e7ce58789adc5204357121',
    messagingSenderId: '584741101684',
    projectId: 'miss-cady-production',
    storageBucket: 'miss-cady-production.appspot.com',
    androidClientId: '584741101684-47fkctrta6rjbd4srf89f1p63pi9nr7t.apps.googleusercontent.com',
    iosClientId: '584741101684-9jimluiv3lnpubloqui82talll9393jk.apps.googleusercontent.com',
    iosBundleId: 'com.misscady.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbdGtS1ejwJKXaPDX6Y6shcfVvIAszD3c',
    appId: '1:75185627539:ios:53d97b013456ed74024866',
    messagingSenderId: '75185627539',
    projectId: 'miss-cady-7f1a1',
    storageBucket: 'miss-cady-7f1a1.appspot.com',
    iosBundleId: 'com.example.missCady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUuk_4mOR8VDzFYKUj4hIiUGVoEpdoavM',
    appId: '1:75185627539:web:23b9f1a162186bab024866',
    messagingSenderId: '75185627539',
    projectId: 'miss-cady-7f1a1',
    authDomain: 'miss-cady-7f1a1.firebaseapp.com',
    storageBucket: 'miss-cady-7f1a1.appspot.com',
  );
}