// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLrTF1jE-QqO-5fYiUm-O7h2hHPnDREh8',
    appId: '1:639757077046:web:88dc514e297cd47ec66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    authDomain: 'shiplan-dad96.firebaseapp.com',
    storageBucket: 'shiplan-dad96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMnQ8hmthIY5W8mgeJhxkC0_Gt_aUg34',
    appId: '1:639757077046:android:948a90173ba55e0bc66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    storageBucket: 'shiplan-dad96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMp72y9mutXlY2U7dSpIIMd-x0JVYYUDE',
    appId: '1:639757077046:ios:088a2216bd81bdbfc66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    databaseURL: 'https://shiplan-dad96-default-rtdb.firebaseio.com',
    storageBucket: 'shiplan-dad96.appspot.com',
    iosBundleId: 'com.kh20azkar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMp72y9mutXlY2U7dSpIIMd-x0JVYYUDE',
    appId: '1:639757077046:ios:3a8b274e1b5e4f27c66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    storageBucket: 'shiplan-dad96.appspot.com',
    iosBundleId: 'com.kh20.shiplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLrTF1jE-QqO-5fYiUm-O7h2hHPnDREh8',
    appId: '1:639757077046:web:a204f2a1733224cfc66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    authDomain: 'shiplan-dad96.firebaseapp.com',
    storageBucket: 'shiplan-dad96.appspot.com',
  );
}