// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUuk_4mOR8VDzFYKUj4hIiUGVoEpdoavM',
    appId: '1:75185627539:web:23b9f1a162186bab024866',
    messagingSenderId: '75185627539',
    projectId: 'miss-cady-7f1a1',
    authDomain: 'miss-cady-7f1a1.firebaseapp.com',
    storageBucket: 'miss-cady-7f1a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMnQ8hmthIY5W8mgeJhxkC0_Gt_aUg34',
    appId: '1:639757077046:android:cbe030700cf0324dc66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    databaseURL: 'https://shiplan-dad96-default-rtdb.firebaseio.com',
    storageBucket: 'shiplan-dad96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMp72y9mutXlY2U7dSpIIMd-x0JVYYUDE',
    appId: '1:639757077046:ios:bbdd77e5abeaf43ec66697',
    messagingSenderId: '639757077046',
    projectId: 'shiplan-dad96',
    databaseURL: 'https://shiplan-dad96-default-rtdb.firebaseio.com',
    storageBucket: 'shiplan-dad96.appspot.com',
    iosBundleId: 'com.app.missCadyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbdGtS1ejwJKXaPDX6Y6shcfVvIAszD3c',
    appId: '1:75185627539:ios:42c87e8a8dcac1ea024866',
    messagingSenderId: '75185627539',
    projectId: 'miss-cady-7f1a1',
    storageBucket: 'miss-cady-7f1a1.appspot.com',
    androidClientId: '75185627539-ocsb6n9vn2scghf21kj9mhqnfgogle57.apps.googleusercontent.com',
    iosClientId: '75185627539-p8n6na0tpt3he66tv97tu9d3nq6odis7.apps.googleusercontent.com',
    iosBundleId: 'com.example.missCadyAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUuk_4mOR8VDzFYKUj4hIiUGVoEpdoavM',
    appId: '1:75185627539:web:9b8a8008f4f82004024866',
    messagingSenderId: '75185627539',
    projectId: 'miss-cady-7f1a1',
    authDomain: 'miss-cady-7f1a1.firebaseapp.com',
    storageBucket: 'miss-cady-7f1a1.appspot.com',
  );
}